import { defineConfig } from 'vite';
import { resolve } from 'path';
import builtInModules from 'builtin-modules';
import fs from 'fs';
import path from 'path';
import react from '@vitejs/plugin-react';
import manifest from './manifest.json' assert { type: 'json' };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => {
  const inProd = mode === 'production';

  // Vault path from .notes/VAULT_PATH
  let vaultPath = process.env.VAULT_PATH;
  if (vaultPath && vaultPath.startsWith('~')) {
    vaultPath = path.join(process.env.HOME, vaultPath.slice(1));
  }

  const PLUGIN_PATH = vaultPath ? path.join(vaultPath, '.obsidian', 'plugins', manifest.id) : null;
  const outDir = inProd ? 'dist' : (PLUGIN_PATH || 'dist');

  // Plugin that creates .hotreload file for Obsidian to detect changes
  const hotReloadPlugin = {
    name: 'hot-reload',
    writeBundle: {
      sequential: true,
      order: 'post',
      handler: () => {
        if (!inProd && PLUGIN_PATH) {
          const hotReloadPath = path.join(PLUGIN_PATH, '.hotreload');
          fs.writeFileSync(hotReloadPath, '');
          console.log(`✓ Created .hotreload file at ${hotReloadPath}`);
        }
      }
    }
  };

  // Plugin that copies manifest.json
  const copyManifestPlugin = {
    name: 'copy-manifest',
    writeBundle() {
      const manifestDst = path.join(outDir, 'manifest.json');
      fs.copyFileSync('manifest.json', manifestDst);
      console.log(`✓ Copied manifest.json to ${manifestDst}`);
    }
  };

  return {
    build: {
      lib: {
        entry: resolve('src/main.ts'),
        name: 'main',
        fileName: () => 'main.js',
        formats: ['cjs'],
      },
      minify: inProd,
      sourcemap: inProd ? false : 'inline',
      cssCodeSplit: false,

      emptyOutDir: inProd,
      outDir,
      rollupOptions: {
        input: {
          main: resolve('src/main.ts'),
        },
        output: {
          banner,
          entryFileNames: 'main.js',
          assetFileNames: 'styles.css',
          format: 'cjs',
        },
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtInModules,
        ],
      },
    },
    plugins: [react(), hotReloadPlugin, copyManifestPlugin],
  };
});
